spring:
 
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/health_care
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: 3j1Q8gWEoZXQV3TBds6CWdALIx2+TsEMsC+G8lYtQTU086bwXzI8JqQV+T1lEoDbZVY48QQUFPqgcTtjMXpPKw==

      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds

openai:
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
