spring:
 
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: ${SECRET-KEY}
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds

openai:
  api:
    key: ${OPENAI-KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
