spring:
  sql:
    init:
      mode: always
#      data-locations: classpath:/data.sql
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
#    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhducdtr70@gmail.com
    password: dwojlufrezqiwoar

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${SECRET-KEY}
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds

openai:
  api:
    key: ${OPENAI-KEY}
    url: https://api.openai.com/v1/chat/completions